### ISSUE TITLE
Running  Error( java.io.FileNotFoundException: )

### ISSUE THREAD

**Issue by corlin** [ldbc/ldbc_snb_datagen_spark#110] opened 2019-11-14 03:11 UTC
When I init run the datagen ,it's get this errors ,how can i fix it ,thx

btw: compile is correcct 

Exception in thread "main" java.io.FileNotFoundException: /var/folders/45/vb0nwkz54ksdr337q1hnp5gm0000gn/T/hadoop-unjar4721217962415496628/LICENSE (Is a directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:125)
	at org.apache.hadoop.util.RunJar.unJar(RunJar.java:94)
	at org.apache.hadoop.util.RunJar.run(RunJar.java:232)
	at org.apache.hadoop.util.RunJar.main(RunJar.java:158)

**Comment by szarnyasg** [comment] 2019-11-14 06:25
Hello @corlin,
this used to be a problem on Mac OS that we thought we fixed, see: https://github.com/ldbc/ldbc_snb_datagen/blob/ad900890f0926601a191e52443aae42e8a14bb06/run.sh#L33-L35
Are you one a Mac and do these lines run on your machine?

**Comment by jackwaudby** [comment] 2019-11-14 11:16
Ran into the same problem, @szarnyasg those lines run on my Mac.

**Comment by corlin** [comment] 2019-11-15 02:21
@szarnyasg yes  i run on macos , this line is running correct not report error  ,like this 
zip -d $LDBC_SNB_DATAGEN_HOME/target/ldbc_snb_datagen-0.4.0-SNAPSHOT-jar-with-dependencies.jar META-INF/LICENSE
deleting: META-INF/LICENSE

**Comment by jackwaudby** [comment] 2019-11-17 19:07
This issue arises in commit [24747f8](https://github.com/ldbc/ldbc_snb_datagen/commit/24747f855a46f599c6c97d3d5a89118f9bd6c503). Caused by the bump from Hadoop 2.6.0 to 2.9.2 in `pom.xml`.

**Comment by szarnyasg** [comment] 2019-11-19 00:44
@corlin this should be fixed by switching to Hadoop 3.2.1, please check the latest version on `master`. Please reopen the issue if the problem persists.

**Comment by szarnyasg** [comment] 2020-04-26 09:27
@jackwaudby reported that this popped up again.

**Closed as completed** 2020-04-26 10:09 UTC
Labels: bug
