### ISSUE TITLE
walkmod.xml is not present and causes NullPointerException

### ISSUE THREAD

**Issue by Prakhar0409** [ldbc/ldbc_snb_datagen_spark#43] opened 2017-09-24 17:16 UTC
After installing hadoop and executing run.sh, it fails with a NullPointerException.

ERROR [main] - /home/hadoop/ldbc_snb_datagen/walkmod.xml is invalid. Please, execute walkmod with -e to see the details

I am assuming that walkmod.xml is a configuration file which is absent. If not, maybe how to get around this can be a wiki/readme instruction

**Comment by ArnauPrat** [comment] 2017-09-25 07:28
Hi @Prakhar0409 ,
Could you please share a link or paste here the full output trace? I can't reproduce the error locally. Meanwhile, if you need to run the generator urgently, you can comment out the corresponding "walkmod-plugin" section in the pom.xml file.
Thanks
app

**Comment by jdellithorpe** [comment] 2017-10-25 22:18
It appears that I have the same problem, here is the output trace:

```
jde@master:~/ldbc_snb_datagen$ sh run.sh
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ldbc_snb_datagen 0.2.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ ldbc_snb_datagen ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.275s
[INFO] Finished at: Wed Oct 25 16:14:33 MDT 2017
[INFO] Final Memory: 8M/961M
[INFO] ------------------------------------------------------------------------
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ldbc_snb_datagen 0.2.7
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] >>> maven-assembly-plugin:2.4:assembly (default-cli) @ ldbc_snb_datagen >>>
[INFO]
[INFO] --- walkmod-maven-plugin:1.0.3:apply (default) @ ldbc_snb_datagen ---
:: loading settings :: url = jar:file:/users/jde/.m2/repository/org/walkmod/walkmod-cmd/3.0.0/walkmod-cmd-3.0.0.jar!/ivysettings.xml
:: loading settings :: url = jar:file:/users/jde/.m2/repository/org/apache/ivy/ivy/2.4.0-rc1/ivy-2.4.0-rc1.jar!/org/apache/ivy/core/settings/ivysettings.xml
:: resolving dependencies :: org.walkmod#walkmod-pmd-plugin-caller;working
	confs: [default]
	found org.walkmod#walkmod-pmd-plugin;2.0.9 in maven2
	[2.0.9] org.walkmod#walkmod-pmd-plugin;latest.integration
	found net.sourceforge.pmd#pmd-core;5.5.2 in maven2
	found com.beust#jcommander;1.48 in maven2
	found commons-io#commons-io;2.4 in maven2
	found jaxen#jaxen;1.1.6 in maven2
	found net.java.dev.javacc#javacc;5.0 in maven2
	found net.sourceforge.saxon#saxon;9.1.0.8 in maven2
	found org.apache.commons#commons-lang3;3.4 in maven2
	found org.ow2.asm#asm;5.0.4 in maven2
	found com.google.code.gson#gson;2.5 in maven2
	found net.sourceforge.pmd#pmd-java;5.5.2 in maven2
	found net.sourceforge.pmd#pmd-javascript;5.5.2 in maven2
	found org.mozilla#rhino;1.7.7 in maven2
	found net.sourceforge.pmd#pmd-jsp;5.5.2 in maven2
	found net.sourceforge.pmd#pmd-plsql;5.5.2 in maven2
	found org.walkmod#javalang;4.8.7 in maven2
	[4.8.7] org.walkmod#javalang;[4.5.0, 5.0)
	found org.walkmod#merger;1.0.1 in maven2
	[1.0.1] org.walkmod#merger;[1.0.1, 2.0)
	found org.walkmod#model-checker;1.1 in maven2
	[1.1] org.walkmod#model-checker;[1.0, 2.0)
	found org.walkmod#javalang-compiler;2.3.7 in maven2
	[2.3.7] org.walkmod#javalang-compiler;[2.0, 3.0)
	found log4j#log4j;1.2.16 in maven2
	found org.walkmod#walkmod-maven-plugin;2.1.7 in maven2
	[2.1.7] org.walkmod#walkmod-maven-plugin;latest.integration
	found org.walkmod#javalang;4.8.7 in maven2
	[4.8.7] org.walkmod#javalang;[2.0, 5.0)
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-api;2.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-api-maven;2.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-spi;2.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-impl-maven;2.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-spi-maven;2.2.1 in maven2
	found org.eclipse.aether#aether-api;1.0.0.v20140518 in maven2
	found org.eclipse.aether#aether-impl;1.0.0.v20140518 in maven2
	found org.eclipse.aether#aether-spi;1.0.0.v20140518 in maven2
	found org.eclipse.aether#aether-util;1.0.0.v20140518 in maven2
	found org.eclipse.aether#aether-connector-basic;1.0.0.v20140518 in maven2
	found org.eclipse.aether#aether-transport-wagon;1.0.0.v20140518 in maven2
	found org.apache.maven#maven-aether-provider;3.2.5 in maven2
	found org.apache.maven#maven-model;3.2.5 in maven2
	found org.codehaus.plexus#plexus-utils;3.0.20 in maven2
	found org.apache.maven#maven-model-builder;3.2.5 in maven2
	found org.codehaus.plexus#plexus-interpolation;1.21 in maven2
	found org.codehaus.plexus#plexus-component-annotations;1.5.5 in maven2
	found org.apache.maven#maven-repository-metadata;3.2.5 in maven2
	found org.apache.maven#maven-settings;3.2.5 in maven2
	found org.apache.maven#maven-settings-builder;3.2.5 in maven2
	found org.sonatype.plexus#plexus-sec-dispatcher;1.3 in maven2
	found org.sonatype.plexus#plexus-cipher;1.7 in maven2
	found com.google.guava#guava;18.0 in maven2
	found org.apache.maven.wagon#wagon-provider-api;2.6 in maven2
	found org.apache.maven.wagon#wagon-file;2.6 in maven2
	found commons-lang#commons-lang;2.6 in maven2
	found org.apache.maven.wagon#wagon-http-lightweight;2.6 in maven2
	found org.apache.maven.wagon#wagon-http-shared;2.6 in maven2
	found org.jsoup#jsoup;1.7.2 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-impl-maven-archive;2.2.1 in maven2
	found org.jboss.shrinkwrap#shrinkwrap-impl-base;1.2.1 in maven2
	found org.jboss.shrinkwrap#shrinkwrap-api;1.2.1 in maven2
	found org.jboss.shrinkwrap#shrinkwrap-spi;1.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-api-maven-archive;2.2.1 in maven2
	found org.jboss.shrinkwrap.resolver#shrinkwrap-resolver-spi-maven-archive;2.2.1 in maven2
	found org.eclipse.sisu#org.eclipse.sisu.plexus;0.3.0.M1 in maven2
	found javax.enterprise#cdi-api;1.0 in maven2
	found javax.annotation#jsr250-api;1.0 in maven2
	found javax.inject#javax.inject;1 in maven2
	found org.eclipse.sisu#org.eclipse.sisu.inject;0.3.0.M1 in maven2
	found org.codehaus.plexus#plexus-compiler-javac;2.3 in maven2
	found org.codehaus.plexus#plexus-compiler-api;2.3 in maven2
	found org.apache.maven#maven-embedder;3.2.5 in maven2
	found org.apache.maven#maven-core;3.2.5 in maven2
	found org.apache.maven#maven-artifact;3.2.5 in maven2
	found org.apache.maven#maven-plugin-api;3.2.5 in maven2
	found org.sonatype.sisu#sisu-guice;3.2.3 in maven2
	found aopalliance#aopalliance;1.0 in maven2
	found org.codehaus.plexus#plexus-classworlds;2.5.2 in maven2
	found org.slf4j#slf4j-api;1.7.5 in maven2
	found commons-cli#commons-cli;1.2 in maven2
	found org.apache.maven#maven-compat;3.2.5 in maven2
	found org.apache.maven.wagon#wagon-provider-api;2.8 in maven2
	found org.walkmod#walkmod-javalang-plugin;3.0.3 in maven2
	[3.0.3] org.walkmod#walkmod-javalang-plugin;[2.0, 4.0)
	found org.walkmod#javalang;4.8.7 in maven2
	[4.8.7] org.walkmod#javalang;[3.1.0, 5.0.0)
	found com.squareup#javapoet;1.8.0 in maven2
	found org.walkmod#javalang-compiler;2.3.7 in maven2
	[2.3.7] org.walkmod#javalang-compiler;[2.0.0, 3.0.0)
:: resolution report :: resolve 1818ms :: artifacts dl 55ms
	:: evicted modules:
	org.walkmod#javalang;[4.1.0, 5.0.0) by [org.walkmod#javalang;4.8.7] in [default]
	org.apache.maven.wagon#wagon-provider-api;2.6 by [org.apache.maven.wagon#wagon-provider-api;2.8] in [default]
	commons-io#commons-io;2.2 by [commons-io#commons-io;2.4] in [default]
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   78  |   0   |   0   |   3   ||   81  |   0   |
	---------------------------------------------------------------------
ERROR [main] - /users/jde/ldbc_snb_datagen/walkmod.xml is invalid. Please, execute walkmod with -e to see the details.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.360s
[INFO] Finished at: Wed Oct 25 16:14:38 MDT 2017
[INFO] Final Memory: 16M/961M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.walkmod.maven.plugins:walkmod-maven-plugin:1.0.3:apply (default) on project ldbc_snb_datagen: Execution default of goal org.walkmod.maven.plugins:walkmod-maven-plugin:1.0.3:apply failed: The model ., whose type is walkmod:commons:file-readerin the architecture pmd cannot be loaded: Sorry, it is impossible to load the bean walkmod:commons:file-reader. Please, assure that it is a valid class name and the library which contains it is in the classpath -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
Not a valid JAR: /users/jde/ldbc_snb_datagen/target/ldbc_snb_datagen-0.2.7-jar-with-dependencies.jar
```

**Comment by ArnauPrat** [comment] 2017-10-26 09:33
I don't understand why this happens, since as far as I know it is not mandatory to have a walkmod.xml to work. @rpau might help on this. 
Meanwhile, you can go to pom.xml and comment out the walkmod plugin. It should work.

**Comment by jdellithorpe** [comment] 2017-10-26 15:57
Commenting it out worked.

**Comment by zx1011240107** [comment] 2018-08-11 04:10
我有同样的问题，请问是怎么解决的呢？

**Comment by szarnyasg** [comment] 2018-08-11 08:31
@zx1011240107 Remove these lines from the `pom.xml` file:

https://github.com/ldbc/ldbc_snb_datagen/blob/b581cfb88f474c39d8d7391461c6eb1c5201bd14/pom.xml#L97-L113

**Comment by szarnyasg** [comment] 2019-11-19 10:34
This issue did not occur for the last year - closing, please reopen if required.

**Closed as completed by szarnyasg** 2019-11-19 10:34 UTC
