### ISSUE TITLE
substitution_parameters is empty

### ISSUE THREAD

**Issue by yuqin11** [ldbc/ldbc_snb_datagen_spark#204] opened 2020-09-14 05:01 UTC
i do as example , but dir substitution_parameters is empty.
```
cp params-csv-basic.ini params.ini
wget http://archive.apache.org/dist/hadoop/core/hadoop-3.2.1/hadoop-3.2.1.tar.gz
tar xf hadoop-3.2.1.tar.gz
export HADOOP_CLIENT_OPTS="-Xmx2G"
# set this to the Hadoop 3.2.1 directory
export HADOOP_HOME=`pwd`/hadoop-3.2.1
# set this to the repository's directory
export LDBC_SNB_DATAGEN_HOME=`pwd`
./run.sh
```

**Comment by yuqin11** [comment] 2020-09-14 05:01
how to

**Comment by szarnyasg** [comment] 2020-09-14 14:10
@yuqin11 thanks for reporting this issue, I could reproduce it with your commands. 

It seems the problem is that the Java framework does not call the substitution parameter generator Python scripts. For the time being, you can run them manually:

```bash
paramgenerator/generateparams.py hadoop substitution_parameters/
paramgenerator/generateparamsbi.py hadoop substitution_parameters/
```

**Comment by szarnyasg** [comment] 2020-09-14 14:28
@yuqin11 it seems I managed to fix it by changing the Python interpreter. The problem was that it invoked the `python` binary which now binds to Python 3 on almost all systems (Ubuntu 18.04/20.04, new Fedora versions, etc.). Let me know whether the patch fixed the issue for you.

**Comment by szarnyasg** [comment] 2020-09-18 12:03
Closing this, for now, feel free to reopen if the problem persists.

**Closed as completed by szarnyasg** 2020-09-18 12:03 UTC

**Comment by yuqin11** [comment] 2020-09-21 08:56
it is still empty.

**Comment by yuqin11** [comment] 2020-09-21 08:57
i changed default version.

**Comment by yuqin11** [comment] 2020-09-21 08:59
(base) [root@VM_76_122_centos ~/ldbc_snb_datagen]# paramgenerator/generateparams.py hadoop substitution_parameters/
loading input for parameter generation

**Comment by yuqin11** [comment] 2020-09-21 09:00
using this terminal would be blocked.

**Comment by yuqin11** [comment] 2020-09-21 09:00
nothing happened.

**Comment by szarnyasg** [comment] 2020-09-21 09:24
Hi @yuqin11,

I've just re-run the script (based on your first post) and it generated the parameters. My machine is running Fedora 32 and my Python version is as follows:

```
$ python2 --version
Python 2.7.18
```

It's entirely possible that your distribution does not have the `python2` binary by default, so please double check this.

**Comment by yuqin11** [comment] 2020-09-21 09:32
is there any package i should include？ i'm sure i have right python version.

**Comment by yuqin11** [comment] 2020-09-21 09:32
(base) [root@VM_76_122_centos ~/ldbc_snb_datagen]# python -V
Python 2.7.5

**Comment by szarnyasg** [comment] 2020-09-21 09:34
There are no extra Python packages required. What does `python2 -V` give?

**Comment by yuqin11** [comment] 2020-09-21 09:34
is there new version i could clone again?
 maybe that will be more easier to solve this problem.

**Comment by szarnyasg** [comment] 2020-09-21 09:36
For the time being, I recommend going for the `stable` branch. Just do a `git pull` to make sure you have the latest commit, d6620b96555af9a1151b158251ae0de4a3fb6447.

**Comment by yuqin11** [comment] 2020-09-21 09:37
does this commit . include Fixes #204?

**Comment by szarnyasg** [comment] 2020-09-21 09:39
Yes, see https://github.com/ldbc/ldbc_snb_datagen/issues/204#ref-commit-d6620b9.

**Comment by yuqin11** [comment] 2020-09-21 09:40
ok ,  i will try this commit again.

**Comment by yuqin11** [comment] 2020-09-21 11:44
problem solved.
1. change default python interpreter
2. pull latest code

**Comment by yuqin11** [comment] 2020-09-21 11:44
thanks.

**Comment by szarnyasg** [comment] 2020-09-21 11:54
Great! Your welcome.
